# Generated by Django 5.2.5 on 2025-10-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled delivery time', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_confirmation',
            field=models.ImageField(blank=True, help_text='Screenshot of payment confirmation', null=True, upload_to='payment_confirmations/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_verified',
            field=models.BooleanField(default=False, help_text='Whether payment has been verified by admin'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled pickup time', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=10),
        ),
    ]
