# Generated by Django 5.2.5 on 2025-10-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_delivery_time_order_payment_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, help_text='Table number for physical sales', max_length=20, null=True),
        ),
    ]
