# Generated by Django 5.2.5 on 2025-11-03 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_table_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, help_text='When payment was verified', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who verified the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
