# Generated by Django 5.2.5 on 2025-11-03 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_payment_verified_at_order_payment_verified_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight in kg for weight-based products', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight in kg for weight-based products', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='product',
            name='available_weights',
            field=models.JSONField(blank=True, default=list, help_text='Available weight increments in kg (e.g., [0.25, 0.5, 0.75, 1.0])'),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_type',
            field=models.CharField(choices=[('per_kg', 'Per Kilogram'), ('fixed', 'Fixed Price')], default='fixed', help_text='Whether price is per kg or fixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per kg for food items, fixed price for drinks/desserts', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'weight_kg')},
        ),
    ]
