# Generated by Django 5.2.5 on 2025-11-03 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight in kg for weight-based products', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.25)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per kg for food items, fixed price for drinks/desserts', max_digits=10, validators=[django.core.validators.MinValueValidator(10.0)]),
        ),
    ]
