# Generated by Django 5.2.5 on 2025-11-03 18:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_cartitem_weight_kg_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight in kg for weight-based products', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight in kg for weight-based products', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per kg for food items, fixed price for drinks/desserts', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='pricing_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('per_kg', 'Per Kilogram')], default='fixed', help_text='Whether price is per kg or fixed', max_length=10),
        ),
    ]
