# Generated by Django 5.2.5 on 2025-10-31 15:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('contact_type', models.CharField(choices=[('general', 'General Inquiry'), ('reservation', 'Table Reservation'), ('catering', 'Catering Service'), ('complaint', 'Complaint'), ('compliment', 'Compliment'), ('suggestion', 'Suggestion'), ('other', 'Other')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('admin_response', models.TextField(blank=True, help_text='Response sent to customer')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(help_text='Brief title for the review', max_length=200)),
                ('comment', models.TextField(help_text='Detailed review comment')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether the review is approved to show on site')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured reviews show in prominent places')),
                ('is_active', models.BooleanField(default=True)),
                ('admin_response', models.TextField(blank=True, help_text='Admin response to this review')),
                ('admin_response_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Review',
                'verbose_name_plural': 'Site Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
