# Generated by Django 5.2.5 on 2025-11-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_review_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitereview',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Whether the review is approved to show on site'),
        ),
    ]
