# Generated by Django 5.2.5 on 2025-11-05 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('salary', 'Salary'), ('bonus', 'Bonus'), ('advance', 'Advance'), ('overtime', 'Overtime'), ('other', 'Other')], default='salary', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(help_text='Manager who processed this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(limit_choices_to={'groups__name__in': ['Worker', 'Waiter', 'Chef', 'Cashier', 'Butcher']}, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worker Payment',
                'verbose_name_plural': 'Worker Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
